# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Suman's musings"
title_separator          : "|"
name                     : "Suman"
description              : "My personal blog"
url                      : "https://suman71.github.io"
baseurl                  : ""
repository               : "suman71/suman71.github.io"
teaser                   : "/assets/images/post-teaser.png"
breadcrumbs              : true
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "suman1971"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  provider               : "facebook"
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : 5
    colorscheme          : "light"
  provider               : "staticman"
  staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : "comment-{@timestamp}"
  format                 : "yml"
  moderation             : true
  path                   : "/_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
reCaptcha:
  enabled                : true
  siteKey                : "6LctjkAUAAAAABSZ5qDTien_PYUJovqWD959BQPc"
  secret                 : "6LctjkAUAAAAAPHuNcEwOKIClWwWpmezjm9pgjrV"
atom_feed:
  path                   : "http://feeds.feedburner.com/sumansmusings"
search                   : true
search_full_content      : true

# SEO Related
google_site_verification :
bing_site_verification   : "74F3220FC04BEDD614F8A384B84D50FA"
yandex_site_verification : "c0841594d1bf7f81"
naver_site_verification  :

# Social Sharing
twitter:
  username               : "oporazito"
facebook:
  username               : "suman1971"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/sumanlogo.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # "Suman"
  links: # An array of links to social media profiles
  
    - "https://facebook.com/suman1971"
    - "https://www.linkedin.com/in/suman19"
    - "https://twitter.com/oporazito"
    - "https://instagram.com/oporazito"
    - "https://plus.google.com/118364840166197656368"
# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-112447738-1"

# Site Author
author:
  name             : "Suman"
  avatar           : "/assets/images/sumanlogo.jpg"
  bio              : "Hydrogeologist, Monitoring and Evaluation Expert, IT Person "
  location         : "Bangladesh"
  email            : suman.rubd@yahoo.com
  uri              : #"https://suman71.github.io"
  home             : null
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "suman1971"
  foursquare       :
  github           :
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : "oporazito"
  lastfm           :
  linkedin         : "https://www.linkedin.com/in/suman19"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : "oporazito"
  vine             :
  weibo            :
  xing             :
  youtube          : "https://www.youtube.com/channel/UCG9X2ksz9z3GTWwyFigUPGw"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Dhaka


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-archives

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
   enabled:
     - year
     - categories
     - tags
   layouts:
     category: archive-taxonomy
     tag: archive-taxonomy
   permalinks:
     category: /categories/:name/
     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
